// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycqrjqqtnjxfezeacozt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcXJqcXF0bmp4ZmV6ZWFjb3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDUxMDgsImV4cCI6MjA3Mzg4MTEwOH0.e6mGi4Ln12HF53mlHfULnPSTtl689ViZSEKd4QoAVjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});